// This file was generated by Rcpp::compileAttributes
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppEigen.h>
#include <Rcpp.h>

using namespace Rcpp;

// sparseTR
List sparseTR(NumericVector start, Function fn, Function gr, Function hs, const List control);
RcppExport SEXP trustOptim_sparseTR(SEXP startSEXP, SEXP fnSEXP, SEXP grSEXP, SEXP hsSEXP, SEXP controlSEXP) {
BEGIN_RCPP
    SEXP __sexp_result;
    {
        Rcpp::RNGScope __rngScope;
        Rcpp::traits::input_parameter< NumericVector >::type start(startSEXP );
        Rcpp::traits::input_parameter< Function >::type fn(fnSEXP );
        Rcpp::traits::input_parameter< Function >::type gr(grSEXP );
        Rcpp::traits::input_parameter< Function >::type hs(hsSEXP );
        Rcpp::traits::input_parameter< const List >::type control(controlSEXP );
        List __result = sparseTR(start, fn, gr, hs, control);
        PROTECT(__sexp_result = Rcpp::wrap(__result));
    }
    UNPROTECT(1);
    return __sexp_result;
END_RCPP
}
// quasiTR
List quasiTR(NumericVector start, Function fn, Function gr, const List control);
RcppExport SEXP trustOptim_quasiTR(SEXP startSEXP, SEXP fnSEXP, SEXP grSEXP, SEXP controlSEXP) {
BEGIN_RCPP
    SEXP __sexp_result;
    {
        Rcpp::RNGScope __rngScope;
        Rcpp::traits::input_parameter< NumericVector >::type start(startSEXP );
        Rcpp::traits::input_parameter< Function >::type fn(fnSEXP );
        Rcpp::traits::input_parameter< Function >::type gr(grSEXP );
        Rcpp::traits::input_parameter< const List >::type control(controlSEXP );
        List __result = quasiTR(start, fn, gr, control);
        PROTECT(__sexp_result = Rcpp::wrap(__result));
    }
    UNPROTECT(1);
    return __sexp_result;
END_RCPP
}
